spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${keycloak.domain}/realms/${keycloak.realm}
server:
  port: 7090
  servlet:
    context-path: /auth
jwt:
  auth:
    converter:
      resource-id: authenticationClientId
keycloak:
  realm: agribridge-app
  domain: localhost:8181
  adminClientId: admin-cli
  adminClientSecret: RffWocE8tj0uwUDnCpZXJWyduAiFnEyM
  client: authenticationClientId
  urls:
    auth: http://${keycloak.domain}