server:
  port: 7010

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - AddResponseHeader=X-Powered-By, CodeWithBisky
        - id: user-route
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - AddResponseHeader=X-Powered-By, CodeWithBisky
        - id: notification-route
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
          filters:
            - AddResponseHeader=X-Powered-By, CodeWithBisky

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  gateway:
    enabled: true
